### ISSUE TITLE
--port param doesnt work

### ISSUE THREAD

**Issue by Mirmuxsin** [jn-jairo/laravel-ngrok#10]
- Version: #.#.#
- PHP Version: 8.1.1
- Laravel Framework Version: 9
- Ngrok Version: 3.1.0

**Describe the bug**
It runs on 4040 port even If I'm putting there port=8000
I'm running this command `php artisan ngrok --port=8000` and it's returning 
```
   GuzzleHttp\Exception\ConnectException 

  cURL error 7: Recv failure: Connection reset by peer (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:4040/api/tunnels
```

**Comment by jn-jairo** [comment]
The port 4040 that you see is the web interface, it is normal, the issue was that the ngrok v3 changed some things and the code wasn't able to get the tunnel url.

Please update to the new release [v2.0.4](https://github.com/jn-jairo/laravel-ngrok/releases/tag/v2.0.4) and make sure your ngrok installation is configured properly by running `ngrok config upgrade --relocate`.
